List<Map<String, String>> songs = [
  {'title': 'Tum Hi Ho', 'singer': 'Arijit Singh'},
  {'title': 'Chaiyya Chaiyya', 'singer': 'Sukhwinder Singh'},
  {'title': 'Kal Ho Naa Ho', 'singer': 'Sonu Nigam'},
  {'title': 'Aankhon Mein Teri', 'singer': 'K.K.'},
  {'title': 'Gerua', 'singer': 'Arijit Singh, Antara Mitra'},
  {'title': 'Tum Se Hi', 'singer': 'Mohit Chauhan'},
  {'title': 'Zara Zara', 'singer': 'Bombay Jayashree'},
  {'title': 'Dil Diyan Gallan', 'singer': 'Atif Aslam'},
  {'title': 'Tujhe Dekha Toh', 'singer': 'Kumar Sanu, Lata Mangeshkar'},
  {'title': 'Mere Haath Mein', 'singer': 'Sonu Nigam, Sunidhi Chauhan'},
  {'title': 'Tere Bina', 'singer': 'A.R. Rahman'},
  {'title': 'Tum Mile', 'singer': 'Neeraj Shridhar'},
  {'title': 'Pee Loon', 'singer': 'Mohit Chauhan'},
  {'title': 'Iktara', 'singer': 'Kavita Seth, Amitabh Bhattacharya'},
  {'title': 'Pehli Nazar Mein', 'singer': 'Atif Aslam'},
  {'title': 'Ae Dil Hai Mushkil', 'singer': 'Arijit Singh'},
  {'title': 'Yeh Haseen Vaadiyan', 'singer': 'S.P. Balasubrahmanyam'},
  {'title': 'Tum Jo Aaye', 'singer': 'Rahat Fateh Ali Khan'},
  {'title': 'Jeena Jeena', 'singer': 'Atif Aslam'},
  {'title': 'Tum Hi Dekho Na', 'singer': 'Sonu Nigam, Alka Yagnik'},
  {'title': 'Luka Chuppi', 'singer': 'Lata Mangeshkar'},
  {'title': 'Tum Mile Dil Khile', 'singer': 'Kumar Sanu, Alka Yagnik'},
  {'title': 'Channa Mereya', 'singer': 'Arijit Singh'},
  {'title': 'Tera Ban Jaunga', 'singer': 'Akhil Sachdeva, Tulsi Kumar'},
  {'title': 'Jiya Dhadak Dhadak Jaye', 'singer': 'Rahat Fateh Ali Khan'},
  {'title': 'Tum Paas Aaye', 'singer': 'Udit Narayan, Alka Yagnik'},
  {'title': 'Tujh Mein Rab Dikhta Hai', 'singer': 'Roop Kumar Rathod'},
  {'title': 'Tere Bina Zindagi Se', 'singer': 'Kishore Kumar, Lata Mangeshkar'},
  {'title': 'Muskurane Ki Wajah', 'singer': 'Arijit Singh'},
  {'title': 'Tere Sang Yaara', 'singer': 'Atif Aslam'},
  {'title': 'Suraj Hua Maddham', 'singer': 'Sonu Nigam, Alka Yagnik'},
  {'title': 'Tera Hone Laga Hoon', 'singer': 'Atif Aslam, Alisha Chinai'},
  {'title': 'Tum Bin Jiya Jaaye Kaise', 'singer': 'Chitra Singh'},
  {'title': 'Main Yahaan Hoon', 'singer': 'Udit Narayan'},
  {'title': 'Jashn-E-Bahaara', 'singer': 'Javed Ali'},
  {'title': 'Yeh Ishq Hai', 'singer': 'Shreya Ghoshal'},
  {'title': 'Dil Diyan Gallan', 'singer': 'Atif Aslam'},
  {'title': 'Tum Hi Aana', 'singer': 'Jubin Nautiyal'},
  {'title': 'Tum Se Hi', 'singer': 'Mohit Chauhan'},
  {'title': 'Agar Tum Saath Ho', 'singer': 'Arijit Singh, Alka Yagnik'},
  {'title': 'Humko Humise Chura Lo', 'singer': 'Lata Mangeshkar, Udit Narayan'},
  {'title': 'Pee Loon', 'singer': 'Mohit Chauhan'},
  {'title': 'Mere Haath Mein', 'singer': 'Sonu Nigam, Sunidhi Chauhan'},
  {'title': 'Tere Bina', 'singer': 'A.R. Rahman'},
  {'title': 'Tum Mile', 'singer': 'Neeraj Shridhar'},
  {'title': 'Pee Loon', 'singer': 'Mohit Chauhan'},
  {'title': 'Iktara', 'singer': 'Kavita Seth, Amitabh Bhattacharya'},
  {'title': 'Pehli Nazar Mein', 'singer': 'Atif Aslam'},
  {'title': 'Ae Dil Hai Mushkil', 'singer': 'Arijit Singh'},
  {'title': 'Yeh Haseen Vaadiyan', 'singer': 'S.P. Balasubrahmanyam'},
  {'title': 'Tum Jo Aaye', 'singer': 'Rahat Fateh Ali Khan'},
  {'title': 'Jeena Jeena', 'singer': 'Atif Aslam'},
];
